config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'
   resources :studios do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
    end
   resources :bookings, only: [:index] do
    resources :reviews, only: [:new, :create]
   end

  patch '/bookings/:id', to: 'bookings#cancel', as: 'cancel'
  post '/bookings/:id', to: 'bookings#confirm', as: 'confirm'
  get '/dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :studio
  has_one :review, dependent: :destroy

  validate :studio_belong_user?
  validates :checkin, presence: true
  validates :checkout, presence: true

  def studio_belong_user?
    array = self.user.studios.all
    # person who is booking the studio
    if array.include?(self.studio_id)
      return false
    else
      return true
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates_uniqueness_of :booking
  validates :description, presence: true
  validates :rating, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :studios
  has_many :bookings
  validates :first_name, presence: true
  validates :last_name, presence: true

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
  end

  def new
    @studio = Studio.find(params[:studio_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.studio_id = params[:studio_id]
    @booking.user = current_user
    @booking.checkin = booking_params[:checkin].split.first
    @booking.checkout = booking_params[:checkin].split.last
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    if @booking.update(booking_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find params[:id]
    @booking.destroy
    redirect_to dashboard_path
  end

  def cancel
    @booking = Booking.find params[:id]
    @booking.status = "cancelled"
    @booking.save
    redirect_to dashboard_path
  end

  def confirm
    @booking = Booking.find params[:id]
    @booking.status = "confirmed"
    @booking.save
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:checkin)
  end
end

app/controllers/pages_controller.rb
# This is the dashboard
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @studios = Studio.all
  end

  def dashboard
    @user = current_user
    @bookings = @user.bookings
    @studios = @user.studios
    @user_studio_bookings = []
    @studios.each do |studio|
      studio.bookings.each do |booking|
        @user_studio_bookings << booking
      end
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save

      redirect_to studio_path(@booking.studio)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController

  skip_before_action :authenticate_user!, only: :index

  def index
    @studios = Studio.where.not(latitude: nil, longitude: nil)

    @markers = @studios.map do |studio|
      {
        lat: studio.latitude,
        lng: studio.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { studio: studio })

      }
    end

    if params["search"].present?
      @studios = Studio.where("category ILIKE ? AND city ILIKE ?","%#{params[:search][:category]}%","%#{params[:search][:city]}%")

    else
    @studios = Studio.all
    end
  end

  def show
    @studio = Studio.find params[:id]
    @booking = Booking.new
    @reviews = @studio.reviews
  end

  def new
    @studio = Studio.new
  end

  def create
    @user = current_user
    @studio = Studio.new(studio_params)
    @studio.user = @user
    if @studio.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
    @studio = Studio.find(params[:id])
  end

  def update
    @studio = Studio.find(params[:id])
    @studio.update(studio_params)
    redirect_to studio_path(@studio)
  end

  def destroy
    @studio = Studio.find params[:id]
    @studio.destroy
    redirect_to dashboard_path
  end

  private

  def studio_params
    params.require(:studio).permit(:name, :description, :address, :photo, :price, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<%= simple_form_for [@studio, @booking] do |f| %>

  <%= f.input :checkin, as: :string, label:"Check-in & Check-out", label_html: { class:"check_in_date"}, input_html: { id: "range_start" } %>
  <%= f.submit "Book the studio", class: 'search-btn mb-3' %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>


<%= simple_form_for [@studio, @booking] do |f| %>

  <%= f.input :checkin, as: :string, label:"Check-in & Check-out", label_html: { class:"check_in_date"},input_html: { id: "range_start" } %>
  <%= f.submit "Book the studio", class: "btn btn-primary" %>
<% end %>

<button> <%= link_to "Go back", studio_path(@studio) %> </button>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>arthub</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
      <% unless current_page? root_path %>
        <%= render 'shared/navbar' %>
      <% end %>
      <%= render 'shared/flashes' %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>


  </body>
</html>

app/views/layouts/studios/new.html.erb
<div class="col-md-8">
  <h1>Create a new studio</h1>

  <%= simple_form_for @studio do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="#home" class="nav-link active" data-toggle="tab">Studios</a>
    </li>
    <li class="nav-item">
        <a href="#profile" class="nav-link" data-toggle="tab">Bookings</a>
    </li>
    <li class="nav-item">
        <a href="#messages" class="nav-link" data-toggle="tab">Booked studio</a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" id="home">
      <h1 class="header">My Studios</h1>
      <div class="d-flex justify-content-around navtab-grid">
        <% if @studios %>
          <% @studios.each do |studio|%>
          <div>
            <%= link_to studio_path(studio) do %>
              <div class="card-trip">
                <div class="p-2">
                   <%= studio.name.capitalize %>
                </div>
                <%= cl_image_tag studio.photo, height: 300, width: 400, crop: :fill %>
              </div>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="profile">
        <h1 class="header">My Bookings</h1>
        <div class="d-flex justify-content-around navtab-gridz">
          <% if @bookings %>
            <% @bookings.each do |booking|%>
            <div>
              <%= link_to studio_path(booking.studio) do %>
                <div class="card-trip">
                  <div>
                    <%= booking.studio.name %>
                  </div>

                  <div>
                    <%= cl_image_tag booking.studio.photo, height: 300, width: 400, crop: :fill %>
                  </div>

                  <div>
                    <%= booking.user.first_name %>
                  </div>

                  <div>
                    <%= booking.status %>
                  </div>

                  <div>
                    <button>
                      <%= link_to "add a review", new_booking_review_path(booking.id,Review.new) %>
                    </button>
                  </div>

                </div>
              <% end %>
              </div>
            <% end %>
          <% else %>
            <p>No bookings</p>
          <% end %>
        </div>
    </div>
    <div class="tab-pane fade" id="messages">
        <h1 class="header">My Studio's Bookings</h1>
        <div class="navtab-gridz">
          <% if @studios&.present? %>

            <%# @studios.each do |studio|%>

              <% @user_studio_bookings.each do |booking| %>
                <div>
                <%= link_to(studio_path(booking.studio)) do %>
                  <div class="card-trip">

                    <div>
                      <h3><%= booking.studio.name %></h3>
                      <p><%= booking.studio.address  %></p>
                    </div>

                    <div>
                      <%= cl_image_tag booking.studio.photo, height: 300, width: 400, crop: :fill %>
                    </div>

                    <div class="test-card-buttons">

                      <button class="btn btn-success text-white">
                        <%= link_to "confirm", confirm_path(booking),method: :post,
                        data: { confirm: "Are you sure?" } %>
                      </button>

                      <button class="btn btn-danger text-white">
                        <%= link_to "cancel", cancel_path(booking),method: :patch,
                        data: { confirm: "Are you sure?" } %>
                      </button>

                    </div>

                  </div>
                <% end %>
                </div>
              <% end %>
            <%# end %>
          <% else %>
            <p>You dont own a studio </p>
          <% end %>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="home-banner">
<%= render 'shared/homepage_navbar' %>

<div class="bannercontainer">
    <div class="sentence">
      <h2>CREATE IN THE RIGHT SPACE</h2>
    </div>

    <div class="form-banner">
        <%= simple_form_for :search, url: studios_path, method: :get  do |f| %>
          <%= f.input_field :category, collection: ["Recording Studio","Photography studio","Dance studio"], include_blank: false, include_hidden: false,
            label: false %>
          <%= f.input_field :city, collection: ["Milan"], include_blank: false, include_hidden: false,
            label: false %>
          <%= f.button :submit, "Search", class: 'search-btn' %>
        <% end %>
    </div>
</div>

</div>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :description %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6 col-sm-offset-4">
      <h3>Add a review</h3>
      <%= simple_form_for [@booking, @review] do |f| %>
      <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
      <%= f.input :description %>
      <%= f.submit "Send your review", class: "search-btn"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_homepage_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-arthub bg-transparent">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo-02.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item-active">
          <%= link_to "", "/", class: "nav-link" %>
        </li>
        <li class="nav-item-active">
          <%= link_to "Add a Studio", "/studios/new", class: "nav-link text-white oh" %>
        </li>
        <li class="nav-item-active">
            <%= link_to "Dashboard", "/dashboard", class: "nav-link text-white oh" %>
        </li>
        <li class="nav-item-active">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: " nav-link text-white oh" %>
            </li>


        <li class="nav-item dropdown ml-2 mr-2 pb-2">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/kmontes417
", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Add a Studio", "/studios/new", class: "navbarlinkclass" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "navbarlinkclass" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "navbarlinkclass" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-arthub-white">
  <%= link_to studios_path, class: "navbar-brand" do %>
    <%= image_tag "logo-03.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item-active">
          <%= link_to "", "/", class: "nav-link" %>
        </li>
        <li class="nav-item-active">
          <%= link_to "Add a Studio", "/studios/new", class: "nav-link text-black oh" %>
        </li>
        <li class="nav-item-active">
            <%= link_to "Dashboard", "/dashboard", class: "nav-link text-black oh" %>
        </li>
        <li class="nav-item-active">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: " nav-link text-black oh"%>
        </li>


        <li class="nav-item dropdown ml-2 mr-2">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/kmontes417
", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Add a Studio", "/studios/new", class: "navbarlinkclass nvblack" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "navbarlinkclass nvblack" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "navbarlinkclass nvblack" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/studios/_infowindow.html.erb
<!-- _infowindow.html.erb
 -->

app/views/studios/edit.html.erb
<!-- edit.html.erb -->
<div class="col-md-8">
  <h1>Edit a studio</h1>

  <%= simple_form_for @studio do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :price %>
    <p>Category</p>
    <%= f.input_field :category, collection: ["Recording Studio","Photography studio","Dance studio"], include_blank: false, include_hidden: false, label: false, class: 'input-field-dropdown' %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :photo %>
    <%= f.button :submit, class: 'search-btn' %>
  <% end %>
</div>

app/views/studios/index.html.erb
<div class="form-banner">
          <%= simple_form_for :search, url: studios_path, method: :get  do |f| %>
          <%= f.input_field :category, collection: ["Recording Studio","Photography studio","Dance studio"], include_blank: false, include_hidden: false,
            label: false, class: 'searchbox-city' %>
          <%= f.input_field :city, collection: ["Milan"], include_blank: false, include_hidden: false,
            label: false, class: 'searchbox-city'%>
          <%= f.button :submit, "Search", class: 'search-btn' %>
          <% end %>
</div>



  <div class="d-flex">
    <div class="cards-container-index">
      <% @studios.each do |studio| %>
      <%= link_to studio_path(studio) do %>
      <div class="card-trip">
        <img src="<%= studio.photo %>">
        <div class="card-trip-infos">
          <div>
            <h2 class="studio-name mb-1"><%= studio.name %></h2>
            <p><%= studio.description.capitalize %></p>
          </div>
          <h2 class="card-trip-pricing">€ <%= studio.price %> /hr</h2>
        </div>
      </div>
        <% end %>
     <% end %>


    </div>

    <div
    id="map"
    style="width: 35vw; top: 110px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

</div>

app/views/studios/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6 col-sm-offset-4">

      <h1>Add a new studio</h1>

        <%= simple_form_for @studio do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :address %>
          <%= f.input :price, label:'Price(€/hr)' %>
          <p>Category</p>
          <%= f.input_field :category, collection: ["recording studio","photography studio","dance studio"], include_blank: false, include_hidden: false, label: false, class: 'input-field-dropdown' %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.button :submit, class: 'search-btn'%>
        <% end %>

   </div>
  </div>
</div>

app/views/studios/show.html.erb
<div class="show-banner" style="position: center bottom; background-size: cover; background-image: url('<%= @studio.photo %>');">
</div>


<div class="container justify-content-center" >
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="studio-wrapper">
        <div class="studio-info">
          <strong><h1><%= @studio.name %></h1></strong>
          <p>Studio owner: <%= @studio.user.first_name.capitalize %> </p>
          <p><%= @studio.category.capitalize %></p>
          <p><%= @studio.address.capitalize %></p>
          <strong><p><%= '%.2f' % @studio.price %> €/hr</p></strong>
        </div>

        <div class="description mb-3">
          <h2>Description</h2>
          <p><%= @studio.description.capitalize %>.</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <%= render 'bookings/new' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="reviews-wrapper">
        <h2>Reviews</h2>
        <% @reviews.each do |review| %>
          <div>
            <div class="test-review-info">
              <img src='<%=review.booking.user.photo%>' alt="user" class="avatar">
              <div class="test-review-user">
                <p>
                  <small><%= review.booking.user.first_name.capitalize %></small>
                </p>
                <p>
                  <small><%= review.created_at.strftime('%B %Y') %></small>
                </p>
              </div>
              <div>
                <% review.rating.times do %>
                  <i class="fa fa-star star" aria-hidden="true"></i>
                <% end %>
              </div>
            </div>
            <div class="review-description">
              <p><%= review.description %></p>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>
</div>